language: node_js
node_js:
- 8
branches:
  only:
  - master
  - develop
before_script:
- npm run lint
before_deploy:
- git checkout -qf master
- git config --global user.email "potz666@gmail.com"
- git config --global user.name "eXigentCoder-CI"
- git config credential.helper "store --file=.git/credentials"
- npm version patch -m "Release %s of the library [skip ci]"
- git push https://$GH_TOKEN@github.com/eXigentCoder/swagger-spec-express.git --all
deploy:
  skip_cleanup: true
  provider: npm
  email: potz666@gmail.com
  api_key:
    secure: w+jG7LjEhVJs0OZNKlK3N4bTI9rb5QJoi/geqVhysq3kCBJS6Ui6VSMGZPrI5tQheOiB7jHkspfAERr8A9BlW0CWDuLyKLmj2CBzdExdABU2sxRtow9SlmaXF3wIaNiIgqvzedQDmdxrcabl1TJxt/Z85t6qoWvlsd67F8tqYa3HATfsW5V5vwuaUUeIS9cGXwicW5Ccc3UicxqlqWdEK7CNMWCwurWqCMCOC9zacfauoG37W3jqEOOvOfVdGRKldy9012PVssz5KYYf4whdEgUG3hG3LChhKp4mNdfHixeMzIFyq9Lx+6NGPyXWosWKJyZkHVNCNuGB9A7h+1QF89jt78KDPTX2d/xWkoqopwI95U/G+Zoc8IAHlhpGLT2mHfAle/udLVuC0HwGhFOGxLnTtFIY95ghe8TtCsOnSCRXhNpTlUo+AykyTXzdH+rXKB0XNvyZCQwhAOPqrRxX3BfzEcXCqKmryOacUf9qfBOtE7y1NsbcMoJntKLmyct1pgqJ/Pmq4lIF3S2jyrQEtx+M2xDMBbv30uMDUpdP1urLAev8e2Wa/l4Z/o4PP1flZso2OOTlJPsqIyYHMBbsA7up9kPvAGfEGhyflm9i3djUBThmtabSipwnX8S2rb7i5Rp2EPxZfHQ5r6TEJe5Yj2O7LGbg/bsOhd53KK2p2Jk=
  on:
    branch: master
    repo: eXigentCoder/swagger-spec-express
env:
  global:
    secure: PbxOr42PYnprCBjbYUey81oDyvN3dMXGVAa7EBi50KKXu71134kMVCVPczYTOXm1fstPsin62nUH+0Jl+pSnvgVmNZHcZkZnjXax/LAoEpm10r5L1NfutspKGz9chbgoAEWeK2Rj0AqseRrNe+scU3kE8gtF+YIiPGHyW2mINzX6iJ9NHLUNpoMm31Mpbr1jbkZjQ25dKhI/WSLavMeBhAm4qmLnZBOf+1Kr7QssxkSmU6/Gis83QAKecjpSQkp2cN31HHYhvaDMrHN9zO3IHnIqIks4k1bRHRRuJvImyHUT49IXYUZ5aFGQ4QAYoAGbhwTcJv+oG1US1HBZWDJI6XkqfAzHvR2quBvrA5rjz2k9dgUmD0lrQuDEFU9fgA1cy5HIgAgqqcvqb8EnsdR/HmVEQ1z628U1VmEc2SvBqtZqc0blKwvsDkWGGk+1XUsN8DiFlIPflqivk0pYu1nZgcDj/KC1+apqWAJus969TN8HKPT3XNxZh1Lk/arETFZhIX4Y43aJ6qV0d0S/jUyHw/G5irC5zMDrkfpOZUUmGXNA3ihCdsC2z7ev0o6Qq2giGNjD2XPI7+9LWczUvKu8k7Y64mUKprDhmSeueLuGPKI51ccAik0B64XpOD4amf4hYfC9+zLctyZPuM1oiHeftGbQ9BPXAxfBsV9kebKBpTE=
